// Offline shell: the app opens without internet once it has been loaded one time.
// Generated by tools/make_sw.py; run it before every deploy so phones pick up the new files.
const VERSION = 'glava-2026-10-03-2008';
const SHELL = [
  './',
  './css/app.css',
  './firebase-config.js',
  './fonts/cormorant-cyrillic.woff2',
  './fonts/cormorant-italic-cyrillic.woff2',
  './fonts/cormorant-italic-latin.woff2',
  './fonts/cormorant-latin.woff2',
  './fonts/fonts.css',
  './fonts/literata-cyrillic.woff2',
  './fonts/literata-italic-cyrillic.woff2',
  './fonts/literata-italic-latin.woff2',
  './fonts/literata-latin.woff2',
  './fonts/onest-cyrillic.woff2',
  './fonts/onest-latin.woff2',
  './icons/apple-touch-icon.png',
  './icons/favicon-64.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/maskable-512.png',
  './index.html',
  './js/app.js',
  './js/cards.js',
  './js/data.js',
  './js/db.js',
  './js/files.js',
  './js/model.js',
  './js/reader/reader.js',
  './js/reader/speak.js',
  './js/screens/book.js',
  './js/screens/cols.js',
  './js/screens/library.js',
  './js/screens/settings.js',
  './js/screens/stats.js',
  './js/screens/today.js',
  './js/store.js',
  './js/sync.js',
  './js/theme-boot.js',
  './js/ui.js',
  './js/util.js',
  './manifest.webmanifest',
  './tts/player.js',
  './tts/prosody.js',
  './tts/text.js',
  './tts/worker.js',
  './vendor/firebase.js',
  './vendor/foliate-js/comic-book.js',
  './vendor/foliate-js/epub.js',
  './vendor/foliate-js/epubcfi.js',
  './vendor/foliate-js/fb2.js',
  './vendor/foliate-js/fixed-layout.js',
  './vendor/foliate-js/footnotes.js',
  './vendor/foliate-js/mobi.js',
  './vendor/foliate-js/overlayer.js',
  './vendor/foliate-js/paginator.js',
  './vendor/foliate-js/progress.js',
  './vendor/foliate-js/search.js',
  './vendor/foliate-js/text-walker.js',
  './vendor/foliate-js/tts.js',
  './vendor/foliate-js/vendor/fflate.js',
  './vendor/foliate-js/vendor/zip.js',
  './vendor/foliate-js/view.js',
  './vendor/ort/ort.wasm.bundle.min.mjs',
  './vendor/piper/piper_phonemize.mjs'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION)
    .then(c => c.addAll(SHELL.map(u => new Request(u, {cache: 'reload'}))))
    .then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  // The voice cache (glava-voice-*) is kept: voices are large and do not change with the app.
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== VERSION && !k.startsWith('glava-voice')).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Same-origin files: answer from the cache at once, refresh the cache in the background.
// Voices and the speech engine's binaries are left alone: the speech worker keeps its own copy.
self.addEventListener('fetch', e => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;
  if (/\/voices\/|\.wasm$|\.data$|\/private\//.test(url.pathname)) return;
  e.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const hit = await cache.match(req, {ignoreSearch: true}) || (req.mode === 'navigate' ? await cache.match('./') : undefined);
    const net = fetch(req).then(res => { if (res.ok && res.type === 'basic') cache.put(req, res.clone()); return res; }).catch(() => undefined);
    if (hit) { e.waitUntil(net); return hit; }
    return (await net) || new Response('Нет сети', {status: 503, headers: {'Content-Type': 'text/plain; charset=utf-8'}});
  })());
});
