"""Writes sw.js: the list of files the app needs to open offline, stamped with a new version.
Run before every deploy (npm run sw), otherwise phones keep showing the previous version."""
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KEEP_DIRS = ['css', 'js', 'fonts', 'icons', 'tts', 'vendor/foliate-js']
EXTRA = ['index.html', 'manifest.webmanifest', 'firebase-config.js', 'vendor/firebase.js',
         'vendor/ort/ort.wasm.bundle.min.mjs', 'vendor/piper/piper_phonemize.mjs']
SKIP = {'LICENSE', '.DS_Store'}

files = set(EXTRA)
for d in KEEP_DIRS:
    for f in (ROOT / d).rglob('*'):
        if f.is_file() and f.name not in SKIP:
            files.add(f.relative_to(ROOT).as_posix())
shell = ['./'] + sorted('./' + f for f in files)
version = 'glava-' + time.strftime('%Y-%m-%d-%H%M')

(ROOT / 'sw.js').write_text(f"""// Offline shell: the app opens without internet once it has been loaded one time.
// Generated by tools/make_sw.py; run it before every deploy so phones pick up the new files.
const VERSION = '{version}';
const SHELL = {shell!r};

self.addEventListener('install', e => {{
  e.waitUntil(caches.open(VERSION)
    .then(c => c.addAll(SHELL.map(u => new Request(u, {{cache: 'reload'}}))))
    .then(() => self.skipWaiting()));
}});

self.addEventListener('activate', e => {{
  // The voice cache (glava-voice-*) is kept: voices are large and do not change with the app.
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== VERSION && !k.startsWith('glava-voice')).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
}});

// Same-origin files: answer from the cache at once, refresh the cache in the background.
// Voices and the speech engine's binaries are left alone: the speech worker keeps its own copy.
self.addEventListener('fetch', e => {{
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;
  if (/\\/voices\\/|\\.wasm$|\\.data$|\\/private\\//.test(url.pathname)) return;
  e.respondWith((async () => {{
    const cache = await caches.open(VERSION);
    const hit = await cache.match(req, {{ignoreSearch: true}}) || (req.mode === 'navigate' ? await cache.match('./') : undefined);
    const net = fetch(req).then(res => {{ if (res.ok && res.type === 'basic') cache.put(req, res.clone()); return res; }}).catch(() => undefined);
    if (hit) {{ e.waitUntil(net); return hit; }}
    return (await net) || new Response('Нет сети', {{status: 503, headers: {{'Content-Type': 'text/plain; charset=utf-8'}}}});
  }})());
}});
""".replace("', '", "',\n  '").replace("['./'", "[\n  './'").replace("']", "'\n]"), encoding='utf-8')
print(version, len(shell), 'files')
